apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app
spec:
  selector:
    app: register-app
  type: NodePort       # NodePort so you can access it from your host
  ports:
    - port: 8080       # internal cluster port
      targetPort: 8080 # port your container listens on
      nodePort: 30080  # external port on your PC
