apiVersion: v1
kind: Service
metadata:
  name: register-app-service
spec:
  selector:
    app: register-app
  type: NodePort
  ports:
    - port: 8080       # Service port
      targetPort: 8080 # Container port
      nodePort: 30080  # NodePort to access outside Minikube
