apiVersion: v1
kind: Service
metadata:
  name: register-app-service
spec:
  type: ClusterIP
  selector:
    app: register-app
  ports:
    - name: http
      port: 80         # Service port (internal)
      targetPort: 8080 # MUST match containerPort in Deployment
