apiVersion: v1
kind: Service
metadata:
  name: register-app-service
spec:
  selector:
    app: register-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort   # no nodePort field, let Kubernetes assign automatically
